baseurl = "https://jskaza.github.io/safe-with-us"
metaDataFormat = "yaml"
title = "Safe With Us Dog Adoption Event"

[[menu.main]]
    name = "About"
    url = "about"
    weight = 1

[[menu.main]]
    name = "Meet The Dogs!"
    url = "dogs"
    weight = 2 

[params]
    introTitle = "Dog Adoption Day"
    introPhoto = "/img/boylston_place.jpeg"
    logo = "/img/safe_with_us.png"
    locationTitle = "The Residence at Boylston Place"
    locationAddress = "615 Heath St, Chestnut Hill, MA"
    eventDate = "May 14, 2022"

    # Enable the darkmode toggle in header
    darkModeToggle = false
  
    # Enable search in header
    enableSearch = true

    # Custom copyright - optional
    copyright = "Copyright © 2022 - Safe With Us Animal Rescue · All rights reserved"
    favicon = "/fontawesome/paw.svg"

    # Color for the intro details and social links block, not applicable for dark mode
    # Supported values: Any color from TailwindCSS default colors
    # Reference: https://tailwindcss.com/docs/customizing-colors
        ascentColor = "bg-blue-100"

    # The page bundle that is shown on the front page
    frontBundle = "dogs"

[params.homepage.social]
  instagram = "https://www.instagram.com/safewithusanimalrescue/?hl=en"
  facebook = "https://www.facebook.com/safewithusanimalrescue/"


[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true