baseurl = "https://blist.vercel.app"
metaDataFormat = "yaml"
title = "Safe With Us Dog Adoption Event"

[[menu.main]]
    name = "About"
    url = "about"
    weight = 1

[[menu.main]]
    name = "Meet The Dogs!"
    url = "dogs"
    weight = 2 

[params]
    introTitle = "Safe With Us Animal Rescue's Dog Adoption Event"
    introSubtitle = "Event Details"
    introPhoto = "/boylston_place.jpeg"
    logo = "/safe_with_us.png"

    # Enable the darkmode toggle in header
    darkModeToggle = true
  
    # Enable search in header
    enableSearch = true

    # Custom copyright - optional
    copyright = "Copyright © 2021 - Katheryn Fox · All rights reserved"
    favicon = "/favicon.svg"

    # Color for the intro details and social links block, not applicable for dark mode
    # Supported values: Any color from TailwindCSS default colors
    # Reference: https://tailwindcss.com/docs/customizing-colors
        ascentColor = "bg-blue-100"

    # The page bundle that is shown on the front page
    frontBundle = "blog"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  xing = "https://www.xing.com/profile/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"


[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true